title: Living Peacefully
logo: peaceful_life.jpg
description: Our website will present you with the latest information regarding stalking. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
